version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.5.1
    environment:
      http.host: "0.0.0.0"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
    restart: always
    ports:
    - "9200:9200"
    - "9300:9300"
  app:
    image: ortussolutions/commandbox:lucee5-alpine-snapshot
    depends_on:
      - elasticsearch
    restart: always
    environment:
      BOX_INSTALL: "true"
      PORT: 8080
      SSL_PORT: 8443
      ES_HOST: "elasticsearch"
      ES_PORT: 9200
    expose:
      - "8080"
      - "8443"
    volumes:
      - .:/app
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx/conf.d:/etc/nginx/conf.d/
