version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.5.1
    environment:
      http.host: "0.0.0.0"
      discovery.type: single-node
    restart: always
    ports:
    - "9200:9200"
    - "9300:9300"
  app:
    image: ortussolutions/commandbox:lucee5-alpine-snapshot
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: always
    environment:
      BOX_INSTALL: "true"
      PORT: 8081
      SSL_PORT: 8843
      ES_HOST: "elasticsearch"
      ES_PORT: 9200
    ports:
      - "8081:8081"
      - "8091:8009"
    volumes:
      - .:/app
    expose:
      - "8081"
      - "8091"
      - "8843"
