name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      env:
        APP_DIR: ${{ secrets.APP_DIR }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: cd $APP_DIR && git checkout master && git pull && docker-compose restart app
